### ISSUE TITLE
Max-len that we had set is not applying

### ISSUE THREAD

**Issue by justin808** [shakacode/style-guide-javascript#26]
If I add this max-len to the local config for https://github.com/shakacode/bootstrap-loader

https://github.com/shakacode/bootstrap-loader/blob/master/.eslintrc
```yaml
---
extends:
  - eslint-config-shakacode
  - prettier

plugins:
  - prettier

globals:
  __DEBUG__: true
  __BOOTSTRAP_CONFIG__: true

ecmaFeatures:
  restParams: true

rules:
  prettier/prettier: "error"

  space-before-function-paren: [2, "never"]
  import/no-unresolved: 0
  no-underscore-dangle: [ "error", { "allow": [ "__BOOTSTRAP_CONFIG__", "__DEBUG__", "_babelPolyfill" ] } ]

  # https://github.com/benmosher/eslint-plugin-import/issues/340
  import/no-extraneous-dependencies: 0
#  max-len: [2, { "code": 100 }]

```

Max-len that we had set is not applying

Airbnb latest on master
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L195
```js
    // specify the maximum length of a line in your program
    // https://eslint.org/docs/rules/max-len
    'max-len': ['error', 100, 2, {
      ignoreUrls: true,
      ignoreComments: false,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
    }],
```

Ours https://github.com/shakacode/style-guide-javascript/blob/41c571e901989800abeacddaecd40c2b500a7ea7/packages/eslint-config-shakacode/rules/javascript.yml#L26
```yaml
  # Almost identical to airbnb’s version, but adds ignore of `import` statements
  max-len:
    - 2
    -
      code: 100
      tabWidth: 2
      ignoreUrls: true
